package net.magnesiumbackend.amqp;

import net.magnesiumbackend.core.json.JsonProvider;

/**
 * Interface for compile-time generated RabbitMQ wiring classes.
 *
 * <p>Implementations of this interface are generated by the annotation processor
 * for classes containing {@code @QueueListener} methods and {@code @RabbitPublisher}
 * fields. The generated code eliminates runtime reflection by producing explicit
 * listener registration and publisher injection code at compile time.</p>
 *
 * @see QueueListenerRegistry
 * @see net.magnesiumbackend.amqp.annotations.QueueListener
 */
public interface RabbitMQWiring {

    /**
     * Wires up RabbitMQ listeners and publishers for a specific component.
     *
     * <p>This method is called by {@link RabbitMQExtension} during application
     * initialization to set up all messaging infrastructure.</p>
     *
     * @param rabbitMQService the RabbitMQ service for exchange/queue operations
     * @param listenerRegistry the registry for registering listeners
     * @param jsonProvider the JSON provider for message serialization
     */
    void wire(RabbitMQService rabbitMQService, QueueListenerRegistry listenerRegistry, JsonProvider jsonProvider);
}
