package net.magnesiumbackend.shell.engine;

import net.magnesiumbackend.shell.dsl.CommandContext;

/**
 * Interface for compile-time generated command handlers.
 *
 * <p>Generated by the annotation processor. Zero reflection required.</p>
 */
@FunctionalInterface
public interface GeneratedHandler {

    /**
     * Executes the command.
     *
     * @param ctx the command context with parsed arguments
     */
    void execute(CommandContext ctx);
}
