package net.magnesiumbackend.core.annotations.service;

/**
 * Marker interface for all classes generated by the Magnesium annotation processor.
 *
 * <p>This interface serves as a common supertype for all generated classes,
 * enabling identification of generated code at runtime via {@code instanceof} checks
 * or in service loading scenarios.</p>
 *
 * <p>Concrete sub-interfaces define specific generation contracts:</p>
 * <ul>
 *   <li>{@link GeneratedSubscriberClass} - for {@code @Subscribe} method registration</li>
 *   <li>{@link GeneratedEmitProxyClass} - for {@code @Emit} method proxying</li>
 *   <li>{@link GeneratedExceptionHandlerClass} - for exception handler registration</li>
 *   <li>{@link GeneratedRouteRegistrationClass} - for HTTP route registration</li>
 *   <li>{@link GeneratedWebSocketRegistrationClass} - for WebSocket route registration</li>
 * </ul>
 *
 * @see GeneratedSubscriberClass
 * @see GeneratedEmitProxyClass
 * @see GeneratedExceptionHandlerClass
 * @see GeneratedRouteRegistrationClass
 * @see GeneratedWebSocketRegistrationClass
 */
public interface GeneratedClass {
}
