package net.magnesiumbackend.processor.generator;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import net.magnesiumbackend.core.MagnesiumRuntime;
import net.magnesiumbackend.core.annotations.Inject;
import net.magnesiumbackend.core.annotations.Lifecycle;
import net.magnesiumbackend.core.annotations.OnInitialize;
import net.magnesiumbackend.core.annotations.PreDestroy;
import net.magnesiumbackend.core.annotations.RestService;
import net.magnesiumbackend.core.annotations.enums.LifecycleStage;
import net.magnesiumbackend.core.annotations.service.GeneratedServiceClass;
import net.magnesiumbackend.core.services.ServiceRegistry;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.*;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.MirroredTypeException;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;
import java.util.ArrayList;
import java.util.List;
import java.io.IOException;

/**
 * Generates compile-time service wiring code for @RestService annotated classes.
 *
 * <p>For each service, generates a class implementing {@link GeneratedServiceClass}
 * that directly registers the service with the {@link ServiceRegistry}.
 *
 * <p>Follows the same pattern as other generated classes (routes, websockets, etc.)
 * for consistency and zero-reflection runtime.
 *
 * <p>All dependency resolution happens at compile time - no reflection at runtime.
 */
public class ServiceAutoWireGenerator {

    private final ProcessingEnvironment processingEnv;
    private final Elements elementUtils;
    private final Types typeUtils;

    public ServiceAutoWireGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
        this.elementUtils = processingEnv.getElementUtils();
        this.typeUtils = processingEnv.getTypeUtils();
    }

    /**
     * Generates wiring code for a @RestService annotated class.
     *
     * <p>Generates a single class implementing GeneratedServiceClass that:
     * <ul>
     *   <li>Resolves dependencies from ServiceRegistry</li>
     *   <li>Instantiates the service via constructor</li>
     *   <li>Registers the instance with the registry</li>
     * </ul>
     */
    public void generateServiceWiring(TypeElement serviceElement) throws IOException {
        RestService restService = serviceElement.getAnnotation(RestService.class);
        if (restService == null) return;

        String packageName = elementUtils.getPackageOf(serviceElement).getQualifiedName().toString();
        String serviceName = serviceElement.getSimpleName().toString();
        String registrationClassName = serviceName + "__ServiceRegistration";

        // Generate the service registration class
        TypeSpec registrationClass = generateServiceRegistrationClass(serviceElement, registrationClassName);

        JavaFile registrationFile = JavaFile.builder(packageName, registrationClass)
            .addFileComment("Generated by Magnesium ServiceAutoWire - DO NOT EDIT")
            .build();

        registrationFile.writeTo(processingEnv.getFiler());
    }

    /**
     * Generates a class implementing GeneratedServiceClass that wires and registers the service.
     */
    private TypeSpec generateServiceRegistrationClass(TypeElement serviceElement, String className) {
        RestService restService = serviceElement.getAnnotation(RestService.class);
        ClassName serviceClassName = ClassName.get(serviceElement);
        ClassName generatedServiceClass = ClassName.get(GeneratedServiceClass.class);
        ClassName serviceRegistry = ClassName.get(ServiceRegistry.class);
        ClassName magnesiumRuntime = ClassName.get(MagnesiumRuntime.class);

        // Determine the registration type (as() attribute or self)
        ClassName registrationType = getRegistrationType(serviceElement, restService, serviceClassName);

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addSuperinterface(generatedServiceClass)
            .addJavadoc("Generated service registration for {@link $T}.", serviceElement);

        // Add instance field for PreDestroy support
        if (findPreDestroyMethod(serviceElement) != null) {
            classBuilder.addField(serviceClassName, "instance", Modifier.PRIVATE);
        }

        // Implement serviceType() method - returns the registration type (as() or self)
        classBuilder.addMethod(MethodSpec.methodBuilder("serviceType")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(Class.class)
            .addStatement("return $T.class", registrationType)
            .build());

        // Implement priority() method
        int priority = getLifecyclePriority(serviceElement, restService);
        classBuilder.addMethod(MethodSpec.methodBuilder("priority")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(int.class)
            .addStatement("return $L", priority)
            .build());

        // Implement scope() method
        String scope = restService != null ? restService.scope().name() : "SINGLETON";
        classBuilder.addMethod(MethodSpec.methodBuilder("scope")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(String.class)
            .addStatement("return $S", scope)
            .build());

        // Implement register() method with full lifecycle support
        classBuilder.addMethod(generateRegisterMethod(serviceElement, serviceRegistry, magnesiumRuntime, restService, registrationType));

        // Add PreDestroy method if present
        ExecutableElement preDestroyMethod = findPreDestroyMethod(serviceElement);
        if (preDestroyMethod != null) {
            classBuilder.addMethod(generatePreDestroyMethod(serviceElement, preDestroyMethod));
        }

        // Add private helper methods for optional dependencies
        List<DependencyInfo> dependencies = analyzeDependencies(serviceElement);
        for (DependencyInfo dep : dependencies) {
            if (dep.isOptional()) {
                classBuilder.addMethod(generateResolveOptionalMethod(dep, serviceRegistry));
            }
        }

        return classBuilder.build();
    }

    private MethodSpec generateRegisterMethod(TypeElement serviceElement, ClassName serviceRegistry,
                                               ClassName magnesiumRuntime, RestService restService,
                                               ClassName registrationType) {
        MethodSpec.Builder method = MethodSpec.methodBuilder("register")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .addParameter(magnesiumRuntime, "runtime")
            .addParameter(serviceRegistry, "services");

        // Find injectable constructor
        ExecutableElement constructor = findInjectableConstructor(serviceElement);

        // Generate dependency resolution statements
        List<String> argNames = new ArrayList<>();
        int index = 0;

        for (VariableElement param : constructor.getParameters()) {
            String argName = "arg" + index;
            argNames.add(argName);

            Inject inject = param.getAnnotation(Inject.class);
            TypeMirror paramType = param.asType();
            TypeName paramTypeName = TypeName.get(paramType);

            boolean isOptional = inject != null && inject.optional();

            if (isOptional) {
                // Optional dependency - use helper method
                method.addStatement("$T $N = resolveOptional$N(services)",
                    paramTypeName, argName, index);
            } else {
                // Required dependency - get directly from registry
                method.addStatement("$T $N = services.get($T.class)",
                    paramTypeName, argName, paramTypeName);
            }

            index++;
        }

        // Build constructor call
        CodeBlock.Builder args = CodeBlock.builder();
        for (int i = 0; i < argNames.size(); i++) {
            if (i > 0) args.add(", ");
            args.add("$N", argNames.get(i));
        }

        // Check if async initialization
        boolean isAsync = restService != null && restService.async();

        ExecutableElement preDestroyMethod = findPreDestroyMethod(serviceElement);
        if (isAsync) {
            method.beginControlFlow("runtime.executor().submit(() ->");
        }
        if (preDestroyMethod != null) {
            // Store instance for PreDestroy
            method.addStatement("this.instance = new $T($L)",
                serviceElement.asType(), args.build());
            method.addStatement("services.register($T.class, this.instance)",
                registrationType);

            // Call @OnInitialize if present
            ExecutableElement onInitMethod = findOnInitializeMethod(serviceElement);
            if (onInitMethod != null) {
                method.addStatement("this.instance.$N()", onInitMethod.getSimpleName());
            }

            // Register shutdown hook for @PreDestroy
            method.addStatement("runtime.addShutdownHook(() -> $N())", preDestroyMethod.getSimpleName());

        } else {
            // No PreDestroy - simpler path
            method.addStatement("$T instance = new $T($L)",
                serviceElement.asType(), serviceElement.asType(), args.build());
            method.addStatement("services.register($T.class, instance)",
                registrationType);

            // Call @OnInitialize if present
            ExecutableElement onInitMethod = findOnInitializeMethod(serviceElement);
            if (onInitMethod != null) {
                method.addStatement("instance.$N()", onInitMethod.getSimpleName());
            }

        }
        if (isAsync) {
            method.endControlFlow();
        }

        return method.build();
    }

    private MethodSpec generatePreDestroyMethod(TypeElement serviceElement, ExecutableElement preDestroyMethod) {
        return MethodSpec.methodBuilder("destroy")
            .addModifiers(Modifier.PRIVATE)
            .returns(void.class)
            .beginControlFlow("if (this.instance != null)")
            .addStatement("this.instance.$N()", preDestroyMethod.getSimpleName())
            .endControlFlow()
            .build();
    }

    private MethodSpec generateResolveOptionalMethod(DependencyInfo dep, ClassName serviceRegistry) {
        int index = dep.getIndex();

        return MethodSpec.methodBuilder("resolveOptional" + index)
            .addModifiers(Modifier.PRIVATE)
            .returns(dep.getType())
            .addParameter(serviceRegistry, "services")
            .beginControlFlow("try")
            .addStatement("return services.get($T.class)", dep.getType())
            .nextControlFlow("catch ($T e)", ClassName.get(RuntimeException.class))
            .addStatement("return null")
            .endControlFlow()
            .build();
    }

    private int getLifecyclePriority(TypeElement serviceElement, RestService restService) {
        // Check @Lifecycle annotation first
        Lifecycle lifecycle = serviceElement.getAnnotation(Lifecycle.class);
        if (lifecycle != null) {
            // Lower stage number = higher priority (earlier initialization)
            return lifecycle.stage().ordinal();
        }

        return LifecycleStage.INIT.ordinal();
    }

    private ClassName getRegistrationType(TypeElement serviceElement, RestService restService, ClassName defaultType) {
        if (restService == null) {
            return defaultType;
        }

        // Try to get the as() attribute value
        try {
            Class<?> asClass = restService.as();
            if (asClass != void.class) {
                return ClassName.get(asClass);
            }
        } catch (MirroredTypeException e) {
            TypeMirror typeMirror = e.getTypeMirror();
            if (typeMirror.getKind() != TypeKind.VOID) {
                return (ClassName) ClassName.get(typeMirror);
            }
        }

        return defaultType;
    }

    private ExecutableElement findOnInitializeMethod(TypeElement serviceElement) {
        for (Element element : serviceElement.getEnclosedElements()) {
            if (element.getKind() == ElementKind.METHOD &&
                element.getAnnotation(OnInitialize.class) != null) {
                return (ExecutableElement) element;
            }
        }
        return null;
    }

    private ExecutableElement findPreDestroyMethod(TypeElement serviceElement) {
        for (Element element : serviceElement.getEnclosedElements()) {
            if (element.getKind() == ElementKind.METHOD &&
                element.getAnnotation(PreDestroy.class) != null) {
                return (ExecutableElement) element;
            }
        }
        return null;
    }

    private ExecutableElement findInjectableConstructor(TypeElement serviceElement) {
        List<ExecutableElement> constructors = new ArrayList<>(4);

        for (Element element : serviceElement.getEnclosedElements()) {
            if (element.getKind() == ElementKind.CONSTRUCTOR) {
                constructors.add((ExecutableElement) element);
            }
        }

        // Look for constructor with @Inject parameters
        for (ExecutableElement constructor : constructors) {
            for (VariableElement param : constructor.getParameters()) {
                if (param.getAnnotation(Inject.class) != null) {
                    return constructor;
                }
            }
        }

        // Fall back to single public constructor
        if (constructors.size() == 1) {
            return constructors.get(0);
        }

        // Default constructor
        for (ExecutableElement constructor : constructors) {
            if (constructor.getParameters().isEmpty()) {
                return constructor;
            }
        }

        throw new IllegalStateException(
            "No suitable constructor found for " + serviceElement.getQualifiedName());
    }

    private List<DependencyInfo> analyzeDependencies(TypeElement serviceElement) {
        List<DependencyInfo> dependencies = new ArrayList<>();
        ExecutableElement constructor = findInjectableConstructor(serviceElement);

        int index = 0;
        for (VariableElement param : constructor.getParameters()) {
            Inject inject = param.getAnnotation(Inject.class);
            TypeMirror type = param.asType();

            dependencies.add(new DependencyInfo(
                index,
                TypeName.get(type),
                inject != null ? inject.value() : null,
                inject != null && inject.optional()
            ));

            index++;
        }

        return dependencies;
    }

    /**
     * Information about a service dependency.
     */
    private static class DependencyInfo {
        private final int index;
        private final TypeName type;
        private final String qualifier;
        private final boolean optional;

        DependencyInfo(int index, TypeName type, String qualifier, boolean optional) {
            this.index = index;
            this.type = type;
            this.qualifier = qualifier;
            this.optional = optional;
        }

        int getIndex() { return index; }
        TypeName getType() { return type; }
        String getQualifier() { return qualifier; }
        boolean isOptional() { return optional; }
    }
}
